### ISSUE TITLE
Is it possible for support more than 30 solenoids?

### ISSUE THREAD

**Issue by seandoyle** [hpieren/Piattuino#1]
Hi - this is a wonderful project! 

Is it possible to support more solenoids? I'm not not familiar with the Arduino Mega's limits. When I look at the pinout it looks like you're using almost all of the digital pins. Is there a simple way to get more? My brother in law was interested in making a device like yours that would span 3-4 octaves. Perhaps there is some way to use two boards responsible for different parts of the MIDI range. 

Thanks so much for posting this project!

**Comment by hpieren** [comment]
Hello there,
thanks for your respect for my Piattuino project. Regarding your question, yes you easily use another output concept with the famous 74HC595 shift register. Here some examples:

[https://www.arduino.cc/en/tutorial/ShiftOut](url)
[https://www.arduino.cc/reference/en/language/functions/advanced-io/shiftout/](url)

[https://www.hackster.io/MoKo/arduino-controlled-piano-robot-pibot-641a06?utm_source=Hackster.io+newsletter&utm_campaign=29fda74899-EMAIL_CAMPAIGN_2017_07_26&utm_medium=email&utm_term=0_6ff81e3e5b-29fda74899-141333493&mc_cid=29fda74899&mc_eid=407c225f28
](url)

I also use this concept in another project:
[http://www.semprevacanze.it/deutsch/vizulu/ArdaSolSchematics/ArdaSolMonitor001.pdf](url)

Hope this helps you.
Kind Regards
Heinz
